;definitions for the symbols defined in exceptions.s
extern IReserved
extern IDivZero
extern IDebug
extern INMI
extern IBreakPoint
extern IOverflow
extern IBoundRange
extern IOpcodeInval
extern IDevNotAvail
extern IDoubleFault
extern IInvalidTSS
extern ISegNotPresent
extern IStackSegFault
extern IGPF
extern IPageFault
extern IFloatingPointExcept
extern IAlignmentCheck
extern IMachineCheck
extern ISIMDFPExcept
extern IVirtExcept
extern ISecurityExcept
extern IKeyboard
extern CreateIA32IDTEntry

